# Generated by Django 4.2.5 on 2023-10-18 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_alter_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Date_of_Birth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Ip_address',
            field=models.GenericIPAddressField(default='192.168.1.1'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Phone_number',
            field=models.IntegerField(default='09023451234'),
        ),
    ]
